export { default as Input } from './input';
export { default as SelectInput } from './select-input';
export { default as Checkbox } from './checkbox';
export { default as Button } from './button';
export { default as Footer } from './footer';
export { default as FormHome } from './form-home';
export { default as FormAddRelatives } from './form-add-relatives';
export { default as RadioGroup } from './radio-group';
export { default as FamilyData } from './family-data';
